### PR TITLE
Initial set of pic from WH

### PR DESCRIPTION
**Pull request by wolfganghuber**

### CODE REVIEW

**Comment by kevinrue** [comment]
just to say that I've spotted this PR, but since you seem to be still working on it, i'd say ping me when you would like me to merge, thanks!

**Comment by wolfganghuber** [comment]
Dear Kevin, I am done for now, please try merging. Is this what you / the others were thinking of? If too much or some are off-topic, please feel free to reduce.

**Comment by kevinrue** [comment]
Thanks Wolfgang!
I just repositioned what I intended as last (visible) slide to the end, but it looks all otherwise good!
Thanks again

**Comment by kevinrue** [comment]
Also - This is _exactly_ what I was thinking of. I can't speak for the others, but I definitely enjoy the perspective that those pictures offer: how long some familiar names have been contributing to the project, and the beautiful settings of Bioconductor meetings and activities over the years :)

**Pull request merged**
